[tool.isort]
profile = "black"

[tool.pylint]
disable = [
    "missing-function-docstring",
    "missing-module-docstring",
    "missing-class-docstring",
    "fixme",
    "logging-fstring-interpolation"

]
ignored-classes = "evdev.ecodes"

[tool.black]
line-length = 100